import { describe, expect, it } from 'vitest'
import { formatNetscape, parseNetscape } from '../src/netscape.js'

/** A file with every shape the format actually produces in the wild. */
const SAMPLE = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# This file was generated by libcurl! Edit at your own risk.',
  '',
  '.example.com\tTRUE\t/\tFALSE\t1735689600\tsid\tabc123',
  '#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1735689600\ttoken\tsecret',
  'hostonly.example.org\tFALSE\t/app\tFALSE\t0\tsession\tvalue',
  '# a comment that is not a cookie',
  '.space.example\tTRUE\t/\tFALSE\t1893456000\twith space\thello world',
  '',
].join('\n')

describe('parseNetscape', () => {
  it('reads every cookie in the file', () => {
    const { cookies, skipped } = parseNetscape(SAMPLE)
    expect(skipped).toEqual([])
    expect(cookies).toHaveLength(4)

    expect(cookies[0]).toEqual({
      domain: '.example.com',
      path: '/',
      secure: false,
      expiry: 1735689600,
      name: 'sid',
      value: 'abc123',
      httpOnly: false,
    })
    expect(cookies[1]).toMatchObject({ name: 'token', httpOnly: true, secure: true })
    // A host-only cookie keeps no leading dot, and expiry 0 stays a session cookie.
    expect(cookies[2]).toMatchObject({ domain: 'hostonly.example.org', expiry: 0, path: '/app' })
    expect(cookies[3]).toMatchObject({ name: 'with space', value: 'hello world' })
  })

  it('ignores comments and blank lines without reporting them as skips', () => {
    const { cookies, skipped } = parseNetscape('# only a comment\n\n\n')
    expect(cookies).toEqual([])
    expect(skipped).toEqual([])
  })

  it('treats a leading dot and the boolean field as the same fact', () => {
    // Dot without the flag.
    expect(parseNetscape('.a.test\tFALSE\t/\tFALSE\t1\tn\tv').cookies[0]?.domain).toBe('.a.test')
    // Flag without the dot: normalised to the form Firefox stores.
    expect(parseNetscape('b.test\tTRUE\t/\tFALSE\t1\tn\tv').cookies[0]?.domain).toBe('.b.test')
    // Neither.
    expect(parseNetscape('c.test\tFALSE\t/\tFALSE\t1\tn\tv').cookies[0]?.domain).toBe('c.test')
  })

  it('accepts 1/0 as booleans, as some writers emit them', () => {
    const { cookies } = parseNetscape('.d.test\t1\t/\t1\t1\tn\tv')
    expect(cookies[0]).toMatchObject({ domain: '.d.test', secure: true })
  })

  it('reports each unusable line with its number and a reason', () => {
    const { cookies, skipped } = parseNetscape(
      [
        'only\ttwo\tfields', // 1
        '.a.test\tTRUE\t/\tFALSE\tnot-a-number\tn\tv', // 2
        '.b.test\tTRUE\t/\tFALSE\t1\t\tv', // 3: empty name
        '\tTRUE\t/\tFALSE\t1\tn\tv', // 4: empty domain
        '.c.test\tTRUE\t/\tFALSE\t1\tok\tfine', // 5: good
      ].join('\n'),
    )
    expect(cookies).toHaveLength(1)
    expect(skipped.map(skip => skip.line)).toEqual([1, 2, 3, 4])
    expect(skipped[0]?.reason).toMatch(/7 tab-separated fields/)
    expect(skipped[1]?.reason).toMatch(/expiry is not a number/)
    expect(skipped[2]?.reason).toMatch(/empty cookie name/)
    expect(skipped[3]?.reason).toMatch(/malformed domain/)
  })

  it('normalises a path that does not start with a slash', () => {
    expect(parseNetscape('.e.test\tTRUE\tapp\tFALSE\t1\tn\tv').cookies[0]?.path).toBe('/app')
    expect(parseNetscape('.e.test\tTRUE\t\tFALSE\t1\tn\tv').cookies[0]?.path).toBe('/')
  })

  it('treats a negative expiry as a session cookie', () => {
    expect(parseNetscape('.f.test\tTRUE\t/\tFALSE\t-1\tn\tv').cookies[0]?.expiry).toBe(0)
  })

  it('keeps non-ASCII values intact', () => {
    const { cookies } = parseNetscape('.g.test\tTRUE\t/\tFALSE\t1\t会话\t值 with 中文')
    expect(cookies[0]).toMatchObject({ name: '会话', value: '值 with 中文' })
  })
})

describe('formatNetscape', () => {
  it('writes the header, then one tab-separated line per cookie', () => {
    const text = formatNetscape([
      {
        domain: '.example.com',
        path: '/',
        secure: true,
        expiry: 1735689600,
        name: 'sid',
        value: 'abc',
        httpOnly: false,
      },
    ])
    const lines = text.trimEnd().split('\n')
    expect(lines[0]).toBe('# Netscape HTTP Cookie File')
    expect(lines.at(-1)).toBe('.example.com\tTRUE\t/\tTRUE\t1735689600\tsid\tabc')
  })

  it('marks HttpOnly with the prefix curl understands', () => {
    const text = formatNetscape([
      {
        domain: '.example.com',
        path: '/',
        secure: false,
        expiry: 0,
        name: 'token',
        value: 'v',
        httpOnly: true,
      },
    ])
    expect(text).toContain('#HttpOnly_.example.com\tTRUE\t/\tFALSE\t0\ttoken\tv')
  })

  it('is sorted, so two exports of one jar are byte-identical', () => {
    const cookie = (domain: string, name: string) => ({
      domain,
      path: '/',
      secure: false,
      expiry: 1,
      name,
      value: 'v',
      httpOnly: false,
    })
    const first = formatNetscape([
      cookie('.b.test', 'x'),
      cookie('.a.test', 'y'),
      cookie('.a.test', 'a'),
    ])
    const second = formatNetscape([
      cookie('.a.test', 'a'),
      cookie('.b.test', 'x'),
      cookie('.a.test', 'y'),
    ])
    expect(first).toBe(second)

    const dataLines = first
      .trimEnd()
      .split('\n')
      .filter(line => !line.startsWith('#'))
      .map(line => line.split('\t'))
    expect(dataLines.map(fields => fields[0])).toEqual(['.a.test', '.a.test', '.b.test'])
    expect(dataLines.map(fields => fields[5])).toEqual(['a', 'y', 'x'])
  })

  it('strips field separators out of a value rather than emitting a broken line', () => {
    const text = formatNetscape([
      {
        domain: '.x.test',
        path: '/',
        secure: false,
        expiry: 0,
        name: 'n',
        value: 'a\tb\nc',
        httpOnly: false,
      },
    ])
    const line = text.trimEnd().split('\n').at(-1)
    expect(line?.split('\t')).toHaveLength(7)
    expect(line?.endsWith('\tabc')).toBe(true)
  })
})

describe('round trip', () => {
  it('survives format -> parse -> format unchanged', () => {
    const { cookies } = parseNetscape(SAMPLE)
    const once = formatNetscape(cookies)
    const twice = formatNetscape(parseNetscape(once).cookies)
    expect(twice).toBe(once)
  })
})
