/**
 * Profile lookup shared by the HTTP routes and the MCP tools.
 *
 * The API accepts either a profile id or a profile name everywhere an id is expected. That is what
 * makes the VirtualBrowser-compatible aliases usable from existing automation scripts, which pass
 * human names, while the GUI keeps using ids.
 *
 * Security note: a raw client string is **never** handed to the core as an id unless it matches the
 * id shape below. The core stores each profile in `<dataDir>/profiles/<id>/`, so an id that is not
 * validated is a path-traversal candidate. Anything that is not a well-formed id is treated as a
 * name and can only match a profile the store already knows about — the store, not the client,
 * supplies the id that every other handler uses.
 */

import type { Core } from '@vfox/core'
import type { Profile } from '@vfox/shared'

import { conflict, notFound } from './errors.js'

/** Ids are generated by the core; anything else is a name. */
export const PROFILE_ID_PATTERN = /^[A-Za-z0-9._-]{1,128}$/

export function looksLikeProfileId(value: string): boolean {
  return PROFILE_ID_PATTERN.test(value) && value !== '.' && value !== '..'
}

export async function findProfile(core: Core, idOrName: string): Promise<Profile> {
  const wanted = idOrName.trim()
  if (looksLikeProfileId(wanted)) {
    const direct = await core.profiles.get(wanted)
    if (direct) return direct
  }

  const lowered = wanted.toLowerCase()
  const matches = (await core.profiles.list()).filter(
    (profile) => profile.name.toLowerCase() === lowered,
  )

  const first = matches[0]
  if (matches.length === 1 && first) return first
  if (matches.length > 1) {
    throw conflict(
      `Profile name "${idOrName}" is ambiguous (${matches.length} matches) — use the profile id`,
    )
  }
  throw notFound(`Unknown profile: ${idOrName}`)
}

export async function findProfileId(core: Core, idOrName: string): Promise<string> {
  return (await findProfile(core, idOrName)).id
}
